### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by whu-lyh** [graphdeco-inria/reduced-3dgs#4]
```
 ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
          subprocess.run(
        File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1
```
how to solve it? Thanks

**Comment by PanagiotisP** [comment]
Hello! This error message is a bit vague. It could be anything from CUDA not being installed or the respective environment variables not being properly set to some extensions not being properly installed.
